config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/:first_name', to: 'static_pages#welcome'
  get 'gossip/:gossip_id', to: 'static_pages#show_gossip', as: 'show_gossip'
  get '/user/:user_id', to: 'static_pages#show_user', as: "show_user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
	belongs_to :gossip 
	belongs_to :tag
end

app/models/join_table_pm_recipient.rb
class JoinTablePmRecipient < ApplicationRecord
	belongs_to :user
	belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	
	has_many :join_table_pm_recipients
	has_many :users, through: :join_table_pm_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	
	has_many :join_table_pm_recipients
	has_many :private_messages, through: :join_table_pm_recipients

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

  def index	
  	@gossips = Gossip.all
  	puts Gossip.all
  end

  def welcome
  	@first_name = params['first_name']
  end

  def show_gossip
  	@gossip = Gossip.find(params['gossip_id'])
  	puts @gossip
  end
   def show_user
  	@user = User.find(params['user_id'])
  	@user_signin_date = @user.created_at.strftime("Inscrit le %d/%m/%Y") 
  	puts @user_signin_date
  	puts @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
       <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- Font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


  </head>

  <body>
        <!-- HEADER -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "THPotin", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "All", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>


    <%= yield %>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 

  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="row m-3">
	<div class="col-sm-12">
		<h1>The THPotin contact page</h1>
	</div>
	<div class="col-sm-12">
		<p>Tu adores notre app et tu veux nous le dire ? Utilise le formulaire de contact ci-dessous 😇❤️😻</p>
	</div>

	<div class="col-sm-8 offset-sm-2">
		<form>
  <div class="form-group">
    <label for="exampleFormControlInput1">Ton adresse email</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Ton gentil commentaire</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
   <button type="submit" class="btn btn-primary mb-2">Envoyer</button>
</form>
	</div>
</div>

app/views/static_pages/index.html.erb
  	<!-- CONTENT -->
		<div class="row m-3">
			<div class="col-sm-12">
				<h1>Voici le mur des potins les plus secrets de THP Session 7 !</h1>
			</div>
			<div class="row m-3">
				<% @gossips.all.each do |gossip|  %>
					<div class="col-sm-3">
						<div class="card" style="width: 18rem;">
						  <div class="card-body">
						    <h5 class="card-title"><i class="fas fa-book-dead"></i> Gossip #<%=gossip.id%></h5>
						    <h6 class="card-subtitle mb-2 text-muted"><%=gossip.title%></h6>
						    <i class="fas fa-angle-right"></i> <%= link_to "Voir plus", show_gossip_path(gossip.id), class: "card-link" %>
						  </div>
						</div>
						<br>
					</div>
				<% end %>
			</div>

		</div>

app/views/static_pages/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>THPotin - Home</title>
  </head>
  <body>

  	<!-- HEADER -->
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="#">THPotin</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav">
		      <li class="nav-item">
		        <%= link_to "All", team_path, class: "nav-link active" %>
		      </li>
		      <li class="nav-item">
		        <%= link_to "Team", team_path, class: "nav-link" %>
		      </li>
		      <li class="nav-item">
		        <%= link_to "Contact", contact_path, class: "nav-link" %>
		      </li>
		    </ul>
		  </div>
		</nav>

  	<!-- CONTENT -->
		<div class="row m-3">
			<div class="col-sm-12">
				<h1>Voici le détail du super potin : </h1>
			</div>
			<div class="row m-3">
				<div class="col-sm-12">
					<div class="card">
					  <div class="card-header">
					    Gossip #<%= @gossip.id %>
					  </div>
					  <div class="card-body">
					    <h5 class="card-title"><%= @gossip.title %></h5>
					    <blockquote class="blockquote mb-0">
					      <p><%= @gossip.content %></p>
					      <footer class="blockquote-footer">Créé le <%= @gossip.created_at %> <cite title="Source Title">par <%= @gossip.user.first_name %>&nbsp; <%= @gossip.user.last_name %></cite></footer>
					    </blockquote>
					  </div>
					</div>
					 <%= link_to "Revenir à la liste des potins", root_path, class: "badge badge-primary" %>
				</div>

			</div>

		</div>


   
		
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/show_gossip.html.erb
  	<!-- CONTENT -->
		<div class="row m-3">
			<div class="col-sm-12">
				<h1>Voici le détail du super potin #<%=@gossip.id%> </h1>
			</div>
			<div class="row m-3">
					<div class="card">
					  <div class="card-body">
					    <h5 class="card-title"><%=@gossip.title%> <i class="far fa-comment"></i> </h5>
				    	<blockquote class="blockquote mb-0">
				      	<p><%= @gossip.content %></p>
				      	<footer class="blockquote-footer">Créé le <%= @gossip.created_at %> <cite title="Source Title">par <i class="fas fa-user-secret"></i> <%= link_to @gossip.user.first_name, show_user_path(@gossip.user.id)%></cite></footer>
				    	</blockquote>
				  	</div>
					 </div>
					</div>
			</div>
			<div class="row m-3">
				<%= link_to "Revenir à la liste des potins", root_path, class: "badge badge-primary" %>
			</div>

app/views/static_pages/show_user.html.erb
  	<!-- CONTENT -->
		<div class="row m-3">
			<div class="col-sm-12">
				<h1>Fiche utilisateur : </h1>
			</div>
			<div class="row m-3">
				<div class="col-sm-12">
					<div class="card" >
					  <div class="card-body">
					    <h5 class="card-title"><i class="fas fa-user-secret"></i> <%=@user.first_name %> <%=@user.last_name %>, <%=@user.age %> ans</h5>
					    <h6 class="card-subtitle mb-2 text-muted"><%=@user.email %></h6>
					    <p class="card-text"><%=@user.description %></p>
					    <p class="card-text"><small class="text-muted"><%= @user_signin_date%></small></p>
					  </div>
					</div>

					 <%= link_to "Revenir à la liste des potins", root_path, class: "badge badge-primary" %>
				</div>

			</div>

		</div>

app/views/static_pages/team.html.erb
  	<!-- CONTENT -->
		<div class="row m-3">
			<div class="col-sm-12">
				<h1>The THPotin team</h1>
			</div>
			<div class="col-sm-12">
				<p>Voici notre équipe lol mdr 😇❤️😻</p>
			</div>

		</div>

		<div class="row m-3">
			<div class="card col-sm-4 offset-md-1">
			  <div class="card-body">
			    <h5 class="card-title">@Fred</h5>
			    <p class="card-text">Moussaillon THP Session7 - Lyon</p>
			  </div>
			</div>
			<div class="card col-sm-4 offset-md-1 style="width: 18rem;">
			  <div class="card-body">
			    <h5 class="card-title">@Leo</h5>
			    <p class="card-text">Moussaillon THP Session7 - Lyon</p>
			  </div>
			</div>									
		</div>

app/views/static_pages/welcome.html.erb
		<div class="row m-3">
			<div class="col-sm-12">
				<h1>Bienvenue <%= @first_name%></h1>
			</div>
			<div class="col-sm-12">
				<p>Ici c'est notre super site de potins, il est chouette, non ?</p>
					 <%= link_to "Découvre ici tous les potins", root_path, class: "badge badge-primary" %>

			</div>

		</div>